### ISSUE TITLE
No hacen falta dobles llamadas

### ISSUE THREAD

**Issue by RodrigoZepeda** [valperez/EstatregiaVacunacionMX#3]
Por ejemplo línea 121:

```
prueba <- prueba %>% full_join(combinaciones, by=c("FECHA", "ENTIDAD_RES", "MUNICIPIO_RES", "EDAD_GRUPOS") )

prueba <- prueba %>%
  arrange ( ENTIDAD_RES, MUNICIPIO_RES, FECHA, EDAD_GRUPOS)
```

se puede simplificar (y también en términos de velocidad y asignación:

```
prueba <- prueba %>% 
     full_join(combinaciones, by = c("FECHA", "ENTIDAD_RES", "MUNICIPIO_RES", "EDAD_GRUPOS") ) %>%
     arrange(ENTIDAD_RES, MUNICIPIO_RES, FECHA, EDAD_GRUPOS)
```

Ojo que también eliminé los espacios del arrange que estaban ahí y agregué un espacio al `=` del `by` de acuerdo con [las guías de estilo tidyverse](https://style.tidyverse.org/syntax.html).

**Comment by valperez** [comment]
No sabía que existian esas reglas pero tienen todo el sentido del mundo :O
