### ISSUE TITLE
Explicar al compartir

### ISSUE THREAD

**Issue by RodrigoZepeda** [valperez/EstatregiaVacunacionMX#6]
Cuando ya van a ser archivos que se van a quedar (no son borradores o ya son las versiones finales) agregar en el encabezado como comentario la descripción de qué hace el archivo.

**Comment by valperez** [comment]
Okeys pero esto es solo para los codigos verdad, no para las bases de datos ya finales?

**Comment by RodrigoZepeda** [comment]
Sip para bases están los readme
Rod
